#!/bin/bash
# Generate system locale data for all MAN supported languages.
# Called by post-build.sh after the root filesystem is assembled.
#
# Args:
#   $1 = target directory (rootfs staging area)
#   $2 = host directory with toolchain binaries
#
# Three strategies are attempted in order:
#   1. If a native (host-runnable) localedef exists, use it to pre-compile
#      all locales into the target rootfs.  This produces the glibc
#      locale-archive used by CLI tools and setlocale().
#   2. If only a cross-compiled localedef exists (aarch64/x86_64 ELF),
#      install it into the target rootfs and create a first-boot init
#      script (S00locale) that runs localedef on the target itself.
#      This guarantees locale data exists even when the build runs on
#      macOS without qemu-user-static.
#   3. If no localedef is found at all, write /etc/locale.gen and
#      /etc/default/locale so the system is ready for runtime generation.
#      COSMIC and gettext-based desktop apps still translate via their
#      bundled .mo / .ftl files with just LANG set.

set -e

TARGET_DIR="$1"
HOST_DIR="${2:-$TOOLCHAIN_HOST_DIR:-$(dirname "$0")/../../output/host}"
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

LOCALE_DIR="${TARGET_DIR}/usr/lib/locale"
mkdir -p "$LOCALE_DIR"

# --------------------------------------------------------------------------
# Discover all supported locales from the i18n.rs LANGUAGES constant so
# the locale list stays in sync with the language chooser.
# --------------------------------------------------------------------------
# Parse LOCALES array from generate-locales.sh itself (self-maintained list)
# plus any additional locales discovered from the SUPPORTED file.
SUPPORTED_FILE="${HOST_DIR}/usr/share/i18n/SUPPORTED"
LOCALES=()

# Parse the LANGUAGES list from the Rust i18n.rs source to stay in sync.
I18N_RS="${PROJECT_ROOT}/support/man-utilities/src/i18n.rs"
if [ -r "$I18N_RS" ]; then
    # Extract every locale= entry from the LANGUAGES array
    while IFS= read -r line; do
        # lines look like: Language { locale: "en_US", name: "English", ... }
        if echo "$line" | grep -q 'locale:'; then
            loc=$(echo "$line" | sed -n 's/.*locale: *"\([^"]*\)".*/\1/p')
            [ -n "$loc" ] && LOCALES+=("$loc")
        fi
    done < "$I18N_RS"
fi

# Deduplicate and also include any locales from the SUPPORTED file
if [ -r "$SUPPORTED_FILE" ]; then
    while IFS='/' read -r loc enc; do
        loc_base=$(echo "$loc" | tr -d '[:space:]')
        [ -n "$loc_base" ] && LOCALES+=("$loc_base")
    done < "$SUPPORTED_FILE"
fi

# Deduplicate
LOCALES=($(printf "%s\n" "${LOCALES[@]}" | sort -u))

echo "  -> Found ${#LOCALES[@]} supported locales"

# --------------------------------------------------------------------------
# Write /etc/locale.gen with all supported locales
# --------------------------------------------------------------------------
LOCALE_GEN="${TARGET_DIR}/etc/locale.gen"
cat > "$LOCALE_GEN" << 'HEADER'
# MAN Linux Distribution — supported locales
# Generated by scripts/generate-locales.sh
# Run 'locale-gen' on the target to compile these locales.
HEADER
for loc in "${LOCALES[@]}"; do
    echo "${loc}.UTF-8 UTF-8" >> "$LOCALE_GEN"
done
echo "  -> Wrote $LOCALE_GEN ($(( $(wc -l < "$LOCALE_GEN") - 3 )) locales)"

# --------------------------------------------------------------------------
# Strategy 1: Find a native (host-runnable) localedef
# --------------------------------------------------------------------------
LOCALEDEF="${HOST_DIR}/usr/bin/localedef"
if [ ! -x "$LOCALEDEF" ] || ! "$LOCALEDEF" --version >/dev/null 2>&1; then
    # Try host system localedef (won't work on macOS — BSD variant)
    LOCALEDEF="$(command -v localedef 2>/dev/null || true)"
    if [ -n "$LOCALEDEF" ] && ! "$LOCALEDEF" --help 2>&1 | grep -qi "glibc\|GNU"; then
        LOCALEDEF=""
    fi
fi

if [ -n "$LOCALEDEF" ]; then
    echo "  -> Using native localedef: $LOCALEDEF"
    echo "  -> Generating ${#LOCALES[@]} locales"
    success=0
    for loc in "${LOCALES[@]}"; do
        if "$LOCALEDEF" -i "$loc" -f UTF-8 \
            --prefix="$LOCALE_DIR/" "${loc}.UTF-8" 2>/dev/null; then
            success=$((success + 1))
        fi
    done
    echo "  -> Generated $success locale(s) in $LOCALE_DIR"
    echo "  [OK] Locale generation complete"
    exit 0
fi

# --------------------------------------------------------------------------
# Strategy 2: Cross-compiled localedef — install into target + first-boot
# --------------------------------------------------------------------------
# On macOS (or when localedef can't run on the host), we install the
# cross-compiled localedef binary into the target rootfs and create an
# init script that generates all locales on the target at first boot.
# Search in multiple candidate locations: the Buildroot host bin, the
# glibc sysroot, and the glibc build directory.
SRC_LOCALEDEF=""
for candidate in \
    "${HOST_DIR}/bin/localedef" \
    "${HOST_DIR}/usr/bin/localedef" \
    "${HOST_DIR}/aarch64-buildroot-linux-gnu/sysroot/usr/bin/localedef" \
    "${HOST_DIR}/x86_64-buildroot-linux-gnu/sysroot/usr/bin/localedef"; do
    if [ -x "$candidate" ]; then
        SRC_LOCALEDEF="$candidate"
        break
    fi
done
if [ -z "$SRC_LOCALEDEF" ]; then
    # Also check the glibc build directory
    BUILD_LOCALEDEF=$(find "${PROJECT_ROOT}/output" -path "*/build/locale/localedef" -type f 2>/dev/null | head -1)
    if [ -n "$BUILD_LOCALEDEF" ] && [ -x "$BUILD_LOCALEDEF" ]; then
        SRC_LOCALEDEF="$BUILD_LOCALEDEF"
    fi
fi

if [ -n "$SRC_LOCALEDEF" ]; then
    echo "  -> Installing cross-compiled localedef into target rootfs"
    mkdir -p "${TARGET_DIR}/usr/bin"
    cp "$SRC_LOCALEDEF" "${TARGET_DIR}/usr/bin/localedef"
    chmod 0755 "${TARGET_DIR}/usr/bin/localedef"
    echo "  -> Installed /usr/bin/localedef in target"
else
    echo "  -> [WARN] Cross-compiled localedef not found — locale data will be generated at runtime via init script"
fi

# Create the first-boot locale generation init script
INIT_LOCALE_SCRIPT="${TARGET_DIR}/etc/init.d/S00locale"
mkdir -p "${TARGET_DIR}/etc/init.d"

# Generate the list of locales for the init script (one per line)
LOCALE_LIST=""
for loc in "${LOCALES[@]}"; do
    LOCALE_LIST="${LOCALE_LIST} ${loc}.UTF-8"
done

cat > "$INIT_LOCALE_SCRIPT" << LOCALESCRIPT
#!/bin/sh
# First-boot locale generation for MAN Linux.
# Runs localedef for every supported locale so that glibc-based
# system components (CLI tools, setlocale, etc.) are translated.

LOCALE_DIR="\${LOCALE_DIR:-/usr/lib/locale}"
MARKER="\${LOCALE_DIR}/.locales-generated"

# Only run once — skip if already done
if [ -f "\$MARKER" ]; then
    exit 0
fi

if ! command -v localedef >/dev/null 2>&1; then
    exit 0
fi

mkdir -p "\$LOCALE_DIR"
chmod 01777 "\$LOCALE_DIR"

LOCALES="${LOCALE_LIST}"
for loc in \$LOCALES; do
    localedef -i "\${loc%.UTF-8}" -f UTF-8 "\\\$loc" 2>/dev/null || true
done

touch "\$MARKER"
LOCALESCRIPT
chmod +x "$INIT_LOCALE_SCRIPT"
echo "  -> Installed first-boot locale init script at /etc/init.d/S00locale"

# Ensure /var/lib/man directory exists for language preference
mkdir -p "${TARGET_DIR}/var/lib/man"
echo "  -> Ensured /var/lib/man directory exists"

echo "  [OK] Locale setup complete (first-boot generation configured)"
